### ISSUE TITLE
Transfer crashes if Toolbox has not been configured yet or if there are no usernotes at all

### ISSUE THREAD

**Issue by fsvreddit** [fsvreddit/toolboxnotesxfer#13]
[ERROR] Oct 17 13:31:31 2024-10-17T12:31:31.876Z TypeError: usernoteTypes.every is not a function
    at checkUsernoteTypesMapped (src/interactiveTransfer.ts:71:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async (src/interactiveTransfer.ts:31:4)
    at async (node_modules/@devvit/public-api/devvit/internals/menu-items.js:63:4)
    at async executeWithSourceMap (/srv/index.cjs:136375:12)
    at async /srv/index.cjs:122622:27 {
  cause: [TypeError: usernoteTypes.every is not a function]

**Comment by fsvreddit** [comment]
Fixed
